/*LA MIA MAMA VUEL CHE FILA*/
const testoMamaVuelCheFila = [
    "La mia mama vuel che fila il lunes",
    "mi al lunes ciapu le pume un po' d'su si e un po' d'lu là la mia mama",
    "tra fe sina e fe disnè la mia mama vuel che fila mi pus pa filè",
    "",
    "La mia mama vuel che fila il martes",
    "mi al martes giocu le carte",
    "mi al lunes ciapu le pume un po' d'su si e un po' d'lu là la mia mama",
    "tra fe sina e fe disnè la mia mama vuel che fila mi pus pa filè",
    "",
    "La mia mama vuel che fila il mercu",
    "mi al mercu vadu da bertu",
    "mi al martes giocu le carte",
    "mi al lunes ciapu le pume un po' d'su si e un po' d'lu là la mia mama",
    "tra fe sina e fe disnè la mia mama vuel che fila mi pus pa filè",
    "",
    "La mia mama vuel che fila il giobbia",
    "mi al giobbia munt en s' la lobbia",
    "mi al mercu vadu da bertu",
    "mi al martes giocu le carte",
    "mi al lunes ciapu le pume un po' d'su si e un po' d'lu là la mia mama",
    "tra fe sina e fe disnè la mia mama vuel che fila mi pus pa filè",
    "",
    "La mia mama vuel che fila il vennar",
    "mi al vennar gavu la senne",
    "mi al giobbia munt en s' la lobbia",
    "mi al mercu vadu da bertu",
    "mi al martes giocu le carte",
    "mi al lunes ciapu le pume un po' d'su si e un po' d'lu là la mia mama",
    "tra fe sina e fe disnè la mia mama vuel che fila mi pus pa filè",
    "",
    "La mia mama vuel che fila il saba",
    "mi al saba ciapu la paga",
    "mi al vennar gavu la senne",
    "mi al giobbia munt en s' la lobbia",
    "mi al mercu vadu da bertu",
    "mi al martes giocu le carte",
    "mi al lunes ciapu le pume un po' d'su si e un po' d'lu là la mia mama",
    "tra fe sina e fe disnè la mia mama vuel che fila mi pus pa filè",
    "",
    "La mia mama vuel che fila il festa",
    "mi al festa catu la vesta",
    "mi al saba ciapu la paga",
    "mi al vennar gavu la senne",
    "mi al giobbia munt en s' la lobbia",
    "mi al mercu vadu da bertu",
    "mi al martes giocu le carte",
    "mi al lunes ciapu le pume un po' d'su si e un po' d'lu là la mia mama",
    "tra fe sina e fe disnè la mia mama vuel che fila mi pus pa filèèèèèèèèèè!"
];

const testoMariemeVuiMarieme = [
    "Marieme, veui marieme",
    "veui fè 'na mariolà",
    "ca cousta l'on ca cousta",
    "ca cousta l'on ca cousta.",
    "Marieme, veui marieme",
    "veui fè 'na mariolà",
    "ca cousta l'on ca cousta",
    "basta ch'i sia marià.",
    "",
    "A pije 'na fumna biunda",
    "l'è 'na gran disperasiun",
    "i preive a 'i fai la runda",
    "la fa girè i butun",
    "Ohi, ciribiribin!",
    "Tantu cuntent — impertinent —",
    "cala giù dal regiment",
    "— Faramieu — Busiard",
    "— Faramieu — Busiard",
    "— Faramieu c'al munta su;",
    "Cala giù!....",
    "",
    "A pije 'na fumna cita",
    "l'è 'na gran disperasiun",
    "l'è nèn côgià nèn drita",
    "i preive a 'i fai la runda",
    "la fa girè i butun",
    "Ohi, ciribiribin!",
    "Tantu cuntent — impertinent —",
    "cala giù dal regiment",
    "— Faramieu — Busiard",
    "— Faramieu — Busiard",
    "— Faramieu c'al munta su;",
    "Cala giù!....",
    "",
    "A pije 'na fumna grassa",
    "l'è 'na gran disperasiun",
    "la sfunda la pajassa",
    "l'è nèn côgià nèn drita",
    "i preive a 'i fai la runda",
    "la fa girè i butun",
    "Ohi, ciribiribin!",
    "Tantu cuntent — impertinent —",
    "cala giù dal regiment",
    "— Faramieu — Busiard",
    "— Faramieu — Busiard",
    "— Faramieu c'al munta su;",
    "Cala giù!....",
    "",
    "A pijè 'na fumna granda",
    "l'è 'na gran disperasiun",
    "sta nèn cuggè 'n t' la branda",
    "la sfunda la pajassa",
    "l'è nèn côgià nèn drita",
    "i preive a 'i fai la runda",
    "la fa girè i butun",
    "Ohi, ciribiribin!",
    "Tantu cuntent — impertinent —",
    "cala giù dal regiment",
    "— Faramieu — Busiard",
    "— Faramieu — Busiard",
    "— Faramieu c'al munta su;",
    "Cala giù!....",
    "",
    "Veui piè na munfrinotta",
    "ca la vegna dal Monfrà",
    "ca la venda le castagne",
    "ca le venda brusatà",
    "sta nèn cuggè 'n t' la branda",
    "la sfunda la pajassa",
    "l'è nèn côgià nèn drita",
    "i preive a 'i fai la runda",
    "la fa girè i butun",
    "Ohi, ciribiribin!",
    "Tantu cuntent — impertinent —",
    "cala giù dal regiment",
    "— Faramieu — Busiard",
    "— Faramieu — Busiard",
    "— Faramieu c'al munta su;",
    "Cala giù!....",
    "",
    "Veui piè 'na sartora",
    "ca la taca li butun,",
    "ca li taca in 'na manera",
    "ca li taca per dabun",
    "ca le venda brusatà",
    "sta nèn cuggè 'n t' la branda",
    "la sfunda la pajassa",
    "l'è nèn côgià nèn drita",
    "i preive a 'i fai la runda",
    "la fa girè i butun",
    "Ohi, ciribiribin!",
    "Tantu cuntent — impertinent —",
    "cala giù dal regiment",
    "— Faramieu — Busiard",
    "— Faramieu — Busiard",
    "— Faramieu c'al munta su;",
    "Cala giù!....",
    "",
    "Veui piè 'na panatera",
    "ca la fassa i biciulan",
    "ca li fassa in 'na manera",
    "ca y stagu drit in man",
    "ca li taca per dabun",
    "ca le venda brusatà",
    "sta nèn cuggè 'n t' la branda",
    "la sfunda la pajassa",
    "l'è nèn côgià nèn drita",
    "i preive a 'i fai la runda",
    "la fa girè i butun",
    "Ohi, ciribiribin!",
    "Tantu cuntent — impertinent —",
    "cala giù dal regiment",
    "— Faramieu — Busiard",
    "— Faramieu — Busiard",
    "— Faramieu c'al munta su;",
    "Cala giù!....",
    "",
    "E butte e mezze butte",
    "barbeira e grignulin",
    "basta ca y sia da beive",
    "d' la seira a la matin.",
    "ca y stagu drit in man",
    "ca li taca per dabun",
    "ca le venda brusatà",
    "sta nèn cuggè 'n t' la branda",
    "la sfunda la pajassa",
    "l'è nèn côgià nèn drita",
    "i preive a 'i fai la runda",
    "la fa girè i butun",
    "Ohi, ciribiribin!",
    "Tantu cuntent — impertinent —",
    "cala giù dal regiment",
    "— Faramieu — Busiard",
    "— Faramieu — Busiard",
    "— Faramieu c'al munta su;",
    "Cala giù!...."
];

function cantaLaMiaMamaVuelCheFila() {
    $("#lyrics-output").empty(); // Pulisce il testo precedente
    for (let i = 0; i < testoMamaVuelCheFila.length; i++) {
        const riga = testoMamaVuelCheFila[i];
        if (riga.trim() !== "") {
            $("#lyrics-output").append($("<h4>").text(riga));
        } else {
            $("#lyrics-output").append("<br>");
        }
    }
}


function cantaMariemeVuiMarieme() {
    $("#lyrics-output").empty(); // Pulisce il testo precedente
    for (let i = 0; i < testoMariemeVuiMarieme.length; i++) {
        const riga = testoMariemeVuiMarieme[i];
        if (riga.trim() !== "") {
            $("#lyrics-output").append($("<h4>").text(riga));
        } else {
            $("#lyrics-output").append("<br>");
        }
    }
}
